### ISSUE TITLE
Docker exec options

### ISSUE THREAD

**Issue by rossdargan** [philhawthorne/ha-dockermon#1]
I'd love to be able to execute a script using this within another docker. I have a docker container and currently I execute the following from the host:

docker exec alarm-mqtt ./bin/get-mode.pl

What I would love to be able to do is the following as a post:

http://127.0.0.1:8126/container/home-assistant/exec?command=./bin/get-mode.pl

What do you think?

**Comment by rossdargan** [comment]
Actually, instead of /exec simply pass in the data "exec" and the payload.

I'll try and do a pull request tomorrow :)

**Comment by philhawthorne** [comment]
I fully support this! This is a great idea.

**Comment by rossdargan** [comment]
Had my first crack at it: https://github.com/rossdargan/ha-dockermon/blob/master/index.js

NOTE I'm not a node dev, so... sorry! I'm aware of the following issues:

- I'm sure the null check for the cmd property is wrong in js
- I commented out the debug checks because I was being lazy when testing
- all results are prefixed with the unicode  for some reason - I have no idea why!

Apart from those, and the poor formatting it does work. I'll fix up what I can :)

**Comment by philhawthorne** [comment]
Awesome!

I think this should go onto its own endpoint. So, you would call `http://127.0.0.1:8126/container/<container name>/exec`. 

From there, whatever `POST`ed command is issued is sent to Docker. This way, if someone needs to parse additional flags, we can add that as parameters to that endpoint in the future.

I'm happy to make these updates though if you're not comfortable. Feel free to send a PR when you think your side is ready.

Don't worry about the Node stuff, still a learning curve for me too :)
