### ISSUE TITLE
Arm variety available?

### ISSUE THREAD

**Issue by Bodge-IT** [philhawthorne/ha-dockermon#10]
Great and useful little tool.  Thank you for making this available.
Having just moved a lot of home bound microsoervices over to pi docker cluster, I was just wondering how hard this would be to port to Arm for making edible with Pi?

**Comment by philhawthorne** [comment]
Hey Gary check out https://hub.docker.com/r/tribunex/ha-dockermon-pi/

**Comment by Bodge-IT** [comment]
Hey Phil, thanks!  I had looked but was searching for arm not pi!
