### ISSUE TITLE
FYI - Not an issue - Added a template to install ha-dockermon on an unRaid server

### ISSUE THREAD

**Issue by digiblur** [philhawthorne/ha-dockermon#17]
Great docker container by the way!  I added a template to my repo so it would show up in the unRaid plugins/docker container searches.  Allows the users to install the container with just a few clicks.

https://github.com/digiblur/unraid-docker-templates

Screenshots

![image](https://user-images.githubusercontent.com/3240875/41489353-5a1e6bf2-70b5-11e8-9f46-1515f7829b13.png)

![image](https://user-images.githubusercontent.com/3240875/41489375-762a3560-70b5-11e8-805b-3fca73366799.png)

**Comment by philhawthorne** [comment]
That's awesome! Thanks so much.

So is there anything users need to do? Or can they just find it by searching for it now?

**Comment by digiblur** [comment]
Nothing special to do.  If the unRaid users want to install it in their docker stack it is pretty simple for them, they'll just click the install button on the HA-Dockermon entry and the defaults are already filled out, they just hit apply and it pulls the docker from your official docker hub entry and starts the container for them.  Couple clicks and that's it.  

Then like the other containers they have it will notify them about updates if they don't have it set to auto-update, etc.

Just makes for a painless install for the unRaid users, no command line stuff for them and ready to go for the environment.
