### ISSUE TITLE
Not seeing home-assistant container

### ISSUE THREAD

**Issue by finity69x2** [philhawthorne/ha-dockermon#23]
pulled and ran the new container.

Now when I execute the restart shell_command from within Home Assistant after a long pause of a couple of minutes I get the following in the log:

2018-08-17 02:36:42 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `curl http://127.0.0.1:8126/container/home-assistant/restart`, return code: 52
NoneType: None

If I run the command from the console in portainer I get:

![ex](https://user-images.githubusercontent.com/32221243/44252107-1a819b00-a1c9-11e8-80db-647ef64c400c.gif)

As you can see, the other containers I tried to run the get command on worked but running it on home-assistant gets me an error.

**Comment by elRadix** [comment]
you should use the IP address of your machine and not the docker internal ip

**Comment by finity69x2** [comment]
I'm not sure what you mean because I AM using the IP of my host machine (127.0.0.1). 

And I'm sure that has nothing to do with it since that is the only container that doesn't work and I'm using the same format for the commands on the other containers that DO work (see the screen shot above).

**Comment by philhawthorne** [comment]
I noticed in the URL there's a trailing slash,

Could you try run `curl http://127.0.0.1:8126/home-assistant`

I am thinking the `/home-assistant/` might be throwing it off.

**Comment by finity69x2** [comment]
I didn't notice that before but I re-ran the command from the console and got the same result:

![ex](https://user-images.githubusercontent.com/32221243/44294154-b4e0ed80-a260-11e8-95fc-3ce22793ae36.gif)


And besides, I am running the same command inside HA that used to work and now doesn't any longer. You can see the command I'm running in HA from the log I posted above.

Here is the copy of the complete entry in the HA config that doesn't work:

restart_hass: 'curl http://127.0.0.1:8126/container/home-assistant/restart'

**Comment by philhawthorne** [comment]
No problem

I'll have a look at this next week and see what's going on underneath the
hood.

Cheers

**Comment by maxxie85** [comment]
I have the exact same issue, of the 18 containers i'm running 2 are posing this issue. Surprisingly the Home-Assistant container also, and the transmission-openvpn container.

**Comment by maxxie85** [comment]
@finity69x2 

Do you mean I have multiple instances running of the same container? If so no, not for those containers.

However the're launched from a single same docker-compose file. I have a compose file to launch HA_Dockermon and Hass and ther is also a compose file to launch Transmission_OpenVPN which launches the Proxy as well. But I argue that could be a issue because the Grafana stack is also launched from a single compose file and there is no issue with the 3 containers launched from there.

**Comment by glassbase** [comment]
I believe it does not like - or _ in container name after attempting to fix [issue 7](https://github.com/philhawthorne/ha-dockermon/issues/7). 

I have these container names: 
mysql
mysql_backup
ninja
ninja_web
ninja_cron

These pages never load (spinning wheel)
http://10.0.0.8:8126/container/mysql 
http://10.0.0.6:8126/container/ninja

**Comment by finity69x2** [comment]
@maxxie85 

No I mean do you have multiple containers with different container names that were created using the same image?

@glassbase 

I have one container that isn't seen. It's named "home-assistant". I have another container built from the same image that works correctly. It's name is "home-assistant-api".

Before i created the second container above, the "home-assistant" container was working correctly with this. 

I'm pretty sure it has nothing to do with the dashes.

**Comment by philhawthorne** [comment]
I can replicate this.

Adding a `home-assistant-api` container, as well as a `home-assistant` container will only ever return the `home-assistant-api` container.

From what I can see, it is doing a fuzzy match. For example assuming there is a container called `hadockermon`, doing a GET request to `http://127.0.0.1/container/ha` will still return the `hadockermon` container, even though the ID `ha` was specified. Which is a bit strange.

Hopefully once the above is resolved, this will solve what we're seeing here.

**Comment by finity69x2** [comment]
so i could rename the ...-api container to something that doesn't begin with home-assistant and then it will work.

That is strange. 

It's not even looking in alphabetical order either since ...api is after the other one in alphabetical order.

Thanks for looking into this.

**Comment by maxxie85** [comment]
@finity69x2 
No I don't thinks so. I start all containers based on docker-compose so can't be sure.

**Comment by finity69x2** [comment]
@maxxie85 

It looks like Phil has already figured out why it's doing it (see three posts up) but hasn't worked out how to fix it yet.

**Comment by finity69x2** [comment]
@philhawthorne 

I just did some testing...

If it's using fuzzy logic I think it should be considered legally blind!

I renamed the container from "home-assistant-api" to "api-home-assistant" and it still wouldn't work correctly.

But when I renamed it "api-assistant-home" it finally worked.

trying to come up with a useful name that doesn't have some form of "home assistant" included in it is challenging.

Hopefully you can work the bug out.

**Comment by philhawthorne** [comment]
@finity69x2 that's so weird.

I am calling the Node library Dockerode to get the container, so I may have to do a check on what that is actually returning.

**Comment by philhawthorne** [comment]
@finity69x2 

I've made some changes to the dev branch, which should hopefully solve this now.

Do you mind doing a `docker run` against the `:edge` or `:edge-arm` tags, to run the latest version with the fix? 

It should now return a 404 if it can't find the container (instead of never hanging up), and also return the right container.

**Comment by maxxie85** [comment]
@philhawthorne 

Can confirm it's working with the :edge tag.

**Comment by finity69x2** [comment]
I just updated to the :edge version and it's now working as expected.

Thanks!

**Comment by philhawthorne** [comment]
Woot! Thanks for your help and patience.
