### ISSUE TITLE
Stopped Containers returns container not found

### ISSUE THREAD

**Issue by GerardRibas** [philhawthorne/ha-dockermon#26]
Hi @philhawthorne, 

First of all, thanks for your hard job on this project!

Not sure about an issue that is happening to me since commit #25. Seems that the stopped containers are not getting back anymore, instead it returns a 404 status code with body: container not found.

I have been debugging the issue and if add the limit:1 in index.js:377 seems working again. 

https://github.com/philhawthorne/ha-dockermon/pull/25/commits/3ab59ea98b0f704d7397a229d132ae6e7f1cae77#diff-168726dbe96b3ce427e7fedce31bb0bcL377

When you have time, could you please verify if your stopped containers are available in ha-dockermon? Thanks!

**Comment by philhawthorne** [comment]
Hey @GerardRibas 

Interesting! Yup, looks like you're right here. Can also see this.

Thanks for your investigation. I'll play around, see if there's a way I can not use the limit:1 and still have this working. 

Cheers

**Comment by philhawthorne** [comment]
@GerardRibas this should all be fixed now in the latest version. Thanks for taking a look into it.

Cheers
