### ISSUE TITLE
Linked Container

### ISSUE THREAD

**Issue by jchong** [philhawthorne/ha-dockermon#33]
I have a container that is linked to several other containers - the container is named "sabnzbd" and shows up as follows (GET /containers):

"Names":["/hydra2/sabnzbd","/radarr/sabnzbd","/sabnzbd","/sonarr/sabnzbd"]

Is there a way to access this linked container?  I've tried the following but get a "container not found" error:

/container/sabnzbd
/container/hydra2/sabnzbd
/container/radarr/sabnzbd
/container/sonarr/sabnzbd

**Comment by jchong** [comment]
I'm able to access the container if I use the ID like so:

http://127.0.0.1:8126/container/kfdghi3uahdfksjfiwehiurhi3u4hg3894hfksjdhfkehrfiu43yifhiushfiuhfiuy48f73gig2



Here's a snipplet of the output from /containers

"Id":"kfdghi3uahdfksjfiwehiurhi3u4hg3894hfksjdhfkehrfiu43yifhiushfiuhfiuy48f73gig2",
"Names":["/hydra2/sabnzbd","/radarr/sabnzbd","/sabnzbd","/sonarr/sabnzbd"]

**Comment by philhawthorne** [comment]
Ah that's interesting. 

I think I know where the issue is here, thanks for reporting. Will try have a fix out for you to test shortly

**Comment by philhawthorne** [comment]
Hi @jchong I've pushed an update for you to test on the `edge` tag. 

```
docker run -d \
--name=ha-dockermon --restart=always \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /path/to/config:/config \
-p 8126:8126 \
philhawthorne/ha-dockermon:edge
```

Please let me know if you'r now able to control your linked container?

**Comment by jchong** [comment]
Thanks @philhawthorne - it's working as expected

**Comment by philhawthorne** [comment]
Brilliant! I'll push out a release. Thanks for the report.
