### ISSUE TITLE
Component broken on 0.92

### ISSUE THREAD

**Issue by jokerigno** [philhawthorne/ha-dockermon#38]
After update to 0.92 switch and binary sensor doesn't work anymore:

> Integration hadockermon not found when trying to verify its binary_sensor platform.
> Integration hadockermon not found when trying to verify its switch platform.

**Comment by philhawthorne** [comment]
Paging mr @ludeeus 😺

**Comment by ludeeus** [comment]
Good news:
<https://github.com/custom-components/switch.hadockermon/issues/29> I'm aware of it.

Bad news:
I will not be able to fix it until sometime next week (other engagements/project that I really need to prioritize this weekend.), and it will be a breaking change.
Most likely I will combine them (proper component) and place it here <https://github.com/custom-components/hadockermon> based on the [blueprint template](https://github.com/custom-components/blueprint)

_Since this is not an issue with `ha-dockermon`, but a custom_component that "talks" to it, I suggest that you close this issue @philhawthorne and point any users that have issues with the custom_components to their respective repos :)_

**Comment by philhawthorne** [comment]
Thanks @ludeeus much obliged 🎩
