### ISSUE TITLE
won't start after last update

### ISSUE THREAD

**Issue by bingobob** [philhawthorne/ha-dockermon#46]
Hi just updated this morning but got a problem, docker won't restart.

was working great before and v useful, thanks for it.

any ideas?

```
Loading settings from /config
fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/config/configuration.yaml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at loadFile (/usr/src/app/node_modules/convict/lib/convict.js:454:19)
    at /usr/src/app/node_modules/convict/lib/convict.js:613:24
    at Array.forEach (<anonymous>)
    at Object.loadFile (/usr/src/app/node_modules/convict/lib/convict.js:611:13)
    at Object.<anonymous> (/usr/src/app/default_settings.js:55:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ha-dockermon@0.0.13 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ha-dockermon@0.0.13 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-06T06_21_57_082Z-debug.log

```

**Comment by philhawthorne** [comment]
Bugger! Wonder if it is a permissions issue. 

I had the same error, but then realised I put the wrong directory in my -v 

I would try give the configuration 0777 permissions to see if that helps

**Comment by xstrex** [comment]
Hey Phil! Same issue here. Recently update won't start container. 
Already tried chmoding the config dir/file 0777, no go. 

```
Loading settings from /config
Warning: configuration param 'docker_connection.port' not declared in the schema
/usr/src/app/node_modules/convict/lib/convict.js:679
          throw new Error(output);
          ^

Error: docker_connection.host: must be of type String
configuration param 'docker_connection.port.doc' missing from config, did you override its parent?
configuration param 'docker_connection.port.format' missing from config, did you override its parent?
    at Object.validate (/usr/src/app/node_modules/convict/lib/convict.js:679:17)
    at Object.<anonymous> (/usr/src/app/default_settings.js:58:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/index.js:6:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ha-dockermon@0.0.13 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ha-dockermon@0.0.13 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-06T16_30_49_632Z-debug.log
```

**Comment by BeastleeUK** [comment]
> Hey Phil! Same issue here. Recently update won't start container.
> Already tried chmoding the config dir/file 0777, no go.
> 
> ```
> > ha-dockermon@0.0.13 start /usr/src/app
> > node index.js
> 
> Loading settings from /config
> Warning: configuration param 'docker_connection.port' not declared in the schema
> /usr/src/app/node_modules/convict/lib/convict.js:679
>           throw new Error(output);
>           ^
> 
> Error: docker_connection.host: must be of type String
> configuration param 'docker_connection.port.doc' missing from config, did you override its parent?
> configuration param 'docker_connection.port.format' missing from config, did you override its parent?
>     at Object.validate (/usr/src/app/node_modules/convict/lib/convict.js:679:17)
>     at Object.<anonymous> (/usr/src/app/default_settings.js:58:8)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/src/app/index.js:6:14)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ha-dockermon@0.0.13 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ha-dockermon@0.0.13 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-09-06T16_30_49_632Z-debug.log
> ```
> 
> My configuration.yaml is similar to the following:
> 
> ```
> debug: false
> http:
>   port: 8126
>   username: foo
>   password: bar
> docker_connection:
>   type: socket
>   path: /var/run/docker.sock
>   host:
>   port:
> ```

I came here due to the same original issue.  From this thread I was able to create a configuration.yaml that worked. Just remove the host and port lines in your configuration.yaml and it should be fine.   Unfortunately mine starts but then I get 401 errors each time I query it and nothing in the log to explain.

**Comment by philhawthorne** [comment]
Thanks everyone!

The original trace reported by @bingobob was because `node-convict` required a configuration.yaml file. I've fixed this, which means you can start this container without mounting a configuration directory if so desired.

For the other errors, `node-convict` now does some validation regarding the keys and values. As such having 

```yaml
docker_connection:
  type: socket
  path: /var/run/docker.sock
  host:
  port:
```

is no longer supported. For this, you'll need to remove the empty values so it becomes

```yaml
docker_connection:
  type: socket
  path: /var/run/docker.sock
```

This is unfortunately a breaking change, but I have updated the sample configuration YAML file to reflect this.

**Comment by bingobob** [comment]
Working great now, thanks @philhawthorne and btw thanks also for such a great bit of code, was super easy for me to plug in to my existing HA setup.
