### ISSUE TITLE
Information about configuration.yaml and its necessary creation on Raspberry Pi

### ISSUE THREAD

**Issue by ThirteenTX** [philhawthorne/ha-dockermon#50]
I am really new to this and spent about 3 hours tonight. I looked all over for a configuration.yaml file on my pie after installation in the docker directories. I finally caught up with the fact that making it was something I was going to have to do by looking again at the install command with the reference here:

`/path/to/config:`

I thought for sure it would exist or I didn't need it because the blog says:

> The second volume mount is to mount a config directory. You can use this to add a configuration.yaml file to define additional settings like a username and password which must be used to call the service. This mount is optional, and default settings will be used if you don’t set it. See the GitHub repo for the default settings and an example file.

Making me think I was good without one if I couldn't find it. Maybe this is common knowledge and this is a product of me being new to linux but I was surely confused. If nothing else this may help someone else. In fact here is what I typed:

sudo mkdir -p /ha-dockermon/config
sudo nano configuration.yaml

Then I pasted the example and reinstalled and it is up and running. I figured this out after after issue 47 didn't fix it. Today was the first time I have tried it. I have the switches up now in hass.io and it looks great. Thanks for your time making this already and coffee is coming on me.

**Comment by philhawthorne** [comment]
Nice! Yeah my recent changes yesterday broke it 😢 

I pushed an update out to fix this, and I've just tried to run it without specifying a configuration file at all, and it seems to be working for me? 

Are you able to do a `docker pull philhawthorne/ha-dockermon:latest-arm` and then try running again without a configuration file?

So a full `docker run` might look like

`docker run --restart=always -d -p 8126:8126 -v -v /var/run/docker.sock:/var/run/docker.sock philhawthorne/ha-dockermon:latest-arm`

However if you leave the `-v /path/to/config:/config` in your `docker run`, unfortunately this won't work as it will overwrite the default configuration.

**Comment by ThirteenTX** [comment]
Just tried it and seems fine. I guess it makes sense if you weren't going to use a configuration.yaml then having the -v /path/to/config:/config line is not a smart move. Learning more all the time it would seem. Well thanks for getting me over my beginner hurdles and bringing some clarity here. You can close this and thanks for your time and quick turn around on this issue! 😃
