### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bonelessc** [philhawthorne/ha-dockermon#78]
Hi Phil,

Love your work!

I am currently using it to monitor all my containers. I also want to monitor/compare if there are updates available. Most of my containers have an API that state version, but not all of them. Would it be possible to get this info from docker?

Like dockermon, there are various stats listed under ENV (path, node_version, yarn_version, config_dir).  It would be great if this info would be listed under the container stats, is that possible?

**Comment by philhawthorne** [comment]
Thanks @bonelessc 

For the updates available, checkout the `dev` branch (can be installed with the `edge` tag). There is an endpoint for `docker pull`. If a new docker image gets pulled, it fires a webhook. You can then use that webhook to know when a new Docker version is available.

My goal here is to be able to have an automated upgrade of Home Assistant take place when a docker pull completes.

Regarding environment variables, I've just pushed up a new update to the `dev` branch. When you call `GET` on a container, it will now return an array of the envirohment keys for the container. Let me know how it goes for you.

**Comment by bonelessc** [comment]
that works great! thank you so much!!
